######################################################################
# Automatically generated by qmake (3.1) Mon Apr 24 16:32:18 2023
######################################################################

TEMPLATE = app
TARGET = FSUDAQ_Qt6
INCLUDEPATH += .

QT += core widgets charts printsupport

LIBS += -lCAENDigitizer -lcurl

#==== for enable GDB debug
QMAKE_CXXFLAGS += -g
QMAKE_CXXFLAGS_RELEASE = -O0
QMAKE_CFLAGS_RELEASE = -O0

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += ClassData.h \
           ClassDigitizer.h \
           ClassInfluxDB.h\
           CustomThreads.h \
           CustomWidgets.h \
           DigiSettingsPanel.h \
           FSUDAQ.h \
           Histogram1D.h \
           Histogram2D.h \
           Hit.h \
           macro.h \
           MultiBuilder.h \
           qcustomplot.h \
           RegisterAddress.h \
           Scope.h \
           SingleSpectra.h \
           analyzers/Analyser.h \
           analyzers/CoincidentAnalyzer.h \
           analyzers/Cross.h\
           analyzers/EncoreAnalyzer.h \
           analyzers/Isotope.h \
           analyzers/SplitPoleAnalyzer.h \
           analyzers/MUSICAnalyzer.h \
           analyzers/NeutronGamma.h 

SOURCES += ClassDigitizer.cpp \
           DigiSettingsPanel.cpp \
           FSUDAQ.cpp \
           main.cpp \
           ClassInfluxDB.cpp\
           Scope.cpp \
           SingleSpectra.cpp \
           MultiBuilder.cpp \
           qcustomplot.cpp \
           analyzers/Analyser.cpp 
